baseURL: https://docs.easydb.de/
defaultContentLanguageInSubdir: true
languageCode: de
title: easydb documentation
DefaultContentLanguage: de
preserveTaxonomyNames: true
disableKinds:
  - taxonomyTerm

languages:
  de:
    weight: 2
    taxonomies:

    menu:
      main:
        - identifier: techdocs
          name: Technische Dokumentation (EN)
          url: /en/technical
          weight: -930
        - identifier: sysadmin
          url: /en/sysadmin
          name: Systemadministration (EN)
          weight: -950
  en:
    weight: 2
    taxonomies:
      easydb-server: easydb-server.yml
      elasticsearch: elasticsearch.yml
      eas: eas.yml
      fylr: fylr.yml

    permalinks:
      easydb-server.yml: /sysadmin/:section/:slug/
      elasticsearch.yml: /sysadmin/:section/:slug/
      eas.yml: /sysadmin/:section/:slug/
      fylr.yml: /sysadmin/:section/:slug/

  zulu:
    contentDir: intern
    weight: 2

theme: "hugo-doc-theme"
# sectionPagesMenu = "main"

pygmentsCodeFences: true

pygmentsOptions: ""
# Use the Chroma stylesheet
pygmentsUseClasses: true
pygmentsUseClassic: false

# See https://help.farbox.com/pygments.html
pygmentsStyle: "github"
